### ISSUE TITLE
Deleting other people's hooks

### ISSUE THREAD

**Issue by hbechara** [Axelfoley85/discordjs-captain-hook#28]
I keep deleting other people's hooks because I'm an idiot. 
I don't really have a way to solve this but maybe we an make it so people can only delete their own hooks?
It's not necessary, I can also just be better.

**Comment by Axelfoley85** [comment]
Would an additional safety check e.g. DM name as mandatory option solve this? As of now it's just text and hooks are not bound to IDs.

**Comment by hbechara** [comment]
Yeah I think so.

**Comment by Axelfoley85** [comment]
I ended up implementing a drop down menu. I think thats just the better interface since it shows you whats available without having to check the hooksChannel.
